-- Migration: Drop dept_id column from sa_system_user table
-- Purpose: Complete the multi-tenant department isolation fix by removing the obsolete dept_id field
-- Date: 2026-04-24
-- 
-- Background:
-- The dept_id field in sa_system_user table caused cross-tenant data leakage because it was a fixed
-- value that didn't change when users switched tenants. This has been replaced by the sa_system_user_dept
-- table which properly associates users with departments per tenant.
--
-- Prerequisites:
-- 1. Migration 003_alter_system_user_dept_table.sql must be executed (creates sa_system_user_dept table)
-- 2. Migration 004_migrate_user_dept_data.sql must be executed (migrates historical data)
-- 3. All code must be updated to use sa_system_user_dept instead of sa_system_user.dept_id
--
-- Impact:
-- - Removes the dept_id column from sa_system_user table
-- - All department associations now come from sa_system_user_dept table
-- - No data loss - all department data has been migrated to sa_system_user_dept
--
-- Rollback:
-- If you need to rollback, you can re-add the column:
-- ALTER TABLE sa_system_user ADD COLUMN dept_id INT DEFAULT 0 COMMENT '部门ID（已废弃）';

-- Drop the dept_id column
ALTER TABLE sa_system_user DROP COLUMN dept_id;
